#!/usr/bin/env bash

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

# Ask the user if they have Homebrew installed
read -p "Do you have Homebrew installed? (y/n) " brew_installed
if [[ $brew_installed =~ ^[Yy]$ ]]
then
    echo "Installing required applications via Homebrew..."
    brew install --cask alacritty
    brew install neovim
    brew install koekeishiya/formulae/yabai
    brew install koekeishiya/formulae/skhd
    brew install tmux
    brew install fzf
    brew install ripgrep
    brew install xclip
    brew install pngpaste
    brew install lazygit
    brew install --cask sioyek
    brew install --cask lookaway
    brew install mpv
else
    echo "Skipping Homebrew installations."
fi

rm -rf $HOME/.config/alacritty
ln -s $DOTFILES/alacritty $HOME/.config/

rm -rf $HOME/.tmux.conf
ln -s $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf

mkdir -p $HOME/.local/bin

rm -rf $HOME/.config/sioyek
ln -s $DOTFILES/sioyek $HOME/.config/

rm -rf $HOME/.config/yabai
ln -s $DOTFILES/yabai $HOME/.config/

rm -rf $HOME/.config/lazygit
ln -s $DOTFILES/lazygit $HOME/.config/

rm -rf $HOME/.config/scripts
ln -s $DOTFILES/scripts $HOME/.config/

# Ensure the script is executable
chmod +x $HOME/.config/scripts/restart_intermission.sh

ln -s $DOTFILES/scripts/com.user.restartintermission.plist $HOME/Library/LaunchAgents/com.user.restartintermission.plist


rm -rf $HOME/.config/skhd
ln -s $DOTFILES/skhd $HOME/.config/

rm -rf $HOME/.config/mpv
ln -s $DOTFILES/mpv $HOME/.config/

rm -rf $HOME/poshthemes
ln -s $DOTFILES/poshthemes $HOME/

rm -rf $HOME/.local/bin/t
ln -s $DOTFILES/scripts/t $HOME/.local/bin/t

rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim


rm -rf $HOME/.config/ghostty
ln -s $DOTFILES/ghostty $HOME/.config/ghostty

# Ask the user what they want to do with the launch agent
echo "What would you like to do with the Intermission launch agent?"
echo "1. Load"
echo "2. Unload"
echo "3. Do nothing"

read -p "Enter your choice (1/2/3): " answer
case $answer in
    1 ) launchctl load ~/Library/LaunchAgents/com.user.restartintermission.plist
        echo "Launch agent loaded."
        ;;
    2 ) launchctl unload ~/Library/LaunchAgents/com.user.restartintermission.plist
        echo "Launch agent unloaded."
        ;;
    3 ) echo "No action taken."
        ;;
    * ) echo "Invalid response. No action taken."
        ;;
esac

echo "Installation complete."
